main: com.rooxchicken.jjk.JJKPlugin
name: JJKPlugin
version: 0.1
api-version: '1.20'

commands:
   giveitems:
      description: Gives the custom items
      usage: /giveitems
   resetce:
      description: Restores CE to full
      usage: /resetce
   resetcursedtechniques:
      description: Resets all of the cursed techniques
      usage: /resetcursedtechniques
   setgojo:
      description: Sets the gojo
      usage: /setgojo <player>
   setsukuna:
      description: Sets the sukuna
      usage: /setsukuna <player>

depend: [ ProtocolLib ]

