main: com.rooxchicken.jjk.JJKPlugin
name: JJKPlugin
version: 0.1
api-version: '1.20'

commands:
   giveitems:
      description: Gives the custom items
      usage: /giveitems
   resetce:
      description: Restores CE to full
      usage: /resetce
   resetcursedtechniques:
      description: Resets all of the cursed techniques
      usage: /resetcursedtechniques

depend: [ ProtocolLib ]

